### PR TITLE
Ocp sync 0.5.0

### PR DESCRIPTION
**Pull request by jhrozek**
Merged upstream tag 0.5.0

### CODE REVIEW

**Comment by jhrozek** [comment]
the flaky test failed with:
```
  Warning  Failed          1s               kubelet            Error: setup seccomp: from field: unable to load local profile "/var/lib/kubelet/seccomp/operator/spo-binding-enabled/profile-allow-unsafe.json": open /var/lib/kubelet/seccomp/operator/spo-binding-enabled/profile-allow-unsafe.json: no such file or directory
```
we've seen this before but only in CI and the issue seems intermittent. Going to re-run the tests.

**Comment by jhrozek** [comment]
@Vincent056 @saschagrunert PTAL

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
