### PR TITLE
CMP-1672: enricher: Parse SELinux AVC lines that contain multiple permissions

### PR DESCRIPTION
**Pull request by jhrozek**
This is a valid AVC denial message:

type=AVC msg=audit(1666691794.882:1434): avc:  denied  { read write open } for  pid=94509...

Note the three permissions inside the curly braces. It did not match the regex at all and wasn't thus parsed.

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by jhrozek** [comment]
There is no known reproducer, I'm afraid, I just found this by chance when tailing the logs of a largish recording.

I think just making sure that the existing tests pass should be good enough.

**Comment by jhrozek** [comment]
Added PX and doc labels as there's nothing to document or support, this is a straight-up bugfix.

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by jhrozek** [comment]
@xiaojiey if you're doing any tests around selinux recording, you can also add this PR to the mix. I don't think it's critical to include in the first release and the testing amounts to just making sure that recording works.

**Comment by xiaojiey** [comment]
Verification pass with 4.13.0-0.nightly-2022-12-16-040121 + code in the PR.
Just did a profilerecording for regression test.
Steps:
```
1.Install SPO.
$ git log | head
commit d3832eee6a3d3efba72bed7ed0c17f02f55080a0
Author: Jakub Hrozek <jhrozek@redhat.com>
Date:   Sun Oct 30 09:47:58 2022 +0100

    enricher: Parse SELinux AVC lines that contain multiple permissions
    
    This is a valid AVC denial message:
    
    type=AVC msg=audit(1666691794.882:1434): avc:  denied  { read write open } for  pid=94509...
$ make deploy-openshift-dev
2. Enable log Enrisher by command below:
$ oc -n openshift-security-profiles patch spod spod --type=merge -p '{"spec":{"enableLogEnricher":true}}'
3. Create a new namespace mytest. To record by using the enricher, create a ProfileRecording which is using recorder: logs:
$ oc new-project mytest
$ oc label ns mytest spo.x-k8s.io/enable-recording=true 
$ oc apply -f -<<EOF
apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: ProfileRecording
metadata:
  name: test-recording
spec:
  kind: SelinuxProfile
  recorder: logs
  mergeStrategy: containers
  podSelector:
    matchLabels:
      app: hello-openshift
EOF

4. create the severice account with privileged permission:
$ oc create -f -<<EOF
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: spo-record-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: spo-record
  namespace: mytest
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - privileged
  verbs:
  - use
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spo-record
  namespace: mytest
subjects:
- kind: ServiceAccount
  name: spo-record-sa
roleRef:
  kind: Role
  name: spo-record
  apiGroup: rbac.authorization.k8s.io
EOF
5. Add label for ns and create deployment to be recorded:

$ oc label ns mytest security.openshift.io/scc.podSecurityLabelSync=false pod-security.kubernetes.io/enforce=privileged --overwrite=true
$  oc apply -f -<<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-openshift
  namespace: mytest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-openshift
  template:
    metadata:
      labels:
        app: hello-openshift
    spec:
      serviceAccountName: spo-record-sa
      initContainers:
      - name: wait
        image: quay.io/openshifttest/centos:centos7
        command: ["/bin/sh", "-c", "env"]
      containers:
      - name: hello-openshift
        image: quay.io/openshifttest/hello-openshift:multiarch
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      - name: hello-openshift2
        image: quay.io/openshifttest/hello-openshift:multiarch-fedora
        ports:
        - containerPort: 8081
        readinessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
EOF
6. Delete the deployment
$ oc get selinuxprofiles.security-profiles-operator.x-k8s.io
NAME                                    USAGE                                                  STATE
test-recording-hello-openshift-6v7hn    test-recording-hello-openshift-6v7hn_mytest.process    Partial
test-recording-hello-openshift-fvpzc    test-recording-hello-openshift-fvpzc_mytest.process    Partial
test-recording-hello-openshift-z92kx    test-recording-hello-openshift-z92kx_mytest.process    Partial
test-recording-hello-openshift2-6v7hn   test-recording-hello-openshift2-6v7hn_mytest.process   Partial
test-recording-hello-openshift2-fvpzc   test-recording-hello-openshift2-fvpzc_mytest.process   Partial
test-recording-hello-openshift2-z92kx   test-recording-hello-openshift2-z92kx_mytest.process   Partial
7. Delete profilerecording
$ oc delete profilerecordings.security-profiles-operator.x-k8s.io test-recording 
profilerecording.security-profiles-operator.x-k8s.io "test-recording" deleted
$ oc get selinuxprofiles.security-profiles-operator.x-k8s.io
NAME                              USAGE                                            STATE
test-recording-hello-openshift    test-recording-hello-openshift_mytest.process    Installed
test-recording-hello-openshift2   test-recording-hello-openshift2_mytest.process   Installed


```

**Pull request merged**
