### PR TITLE
Import latest upstream

### PR DESCRIPTION
**Pull request by jhrozek**
The purpose is to make sure OCP CI still runs and that we can create downstream builds

### CODE REVIEW

**Comment by jhrozek** [comment]
@xiaojiey I will go through the commits and add here what has some test impact
@sheriff-rh I will check what changes do we need to do in our docs.

But I don't expect either of you to go through 356 commits. This is a busy project - the last import was in mid-November..

**Comment by jhrozek** [comment]
ok, gotta upgrade go..

**Comment by jhrozek** [comment]
This is the part that requires 1.20:
```
 # sigs.k8s.io/security-profiles-operator/internal/pkg/util
internal/pkg/util/containers.go:58: fmt.Errorf call has more than one error-wrapping directive %w
# sigs.k8s.io/security-profiles-operator/internal/pkg/artifact
internal/pkg/artifact/artifact.go:335: fmt.Errorf call has more than one error-wrapping directive %w 
```
I opened https://github.com/openshift/release/pull/37485 to use the new go release

**Comment by Vincent056** [comment]
> quite unlikely that they would run fine upstream but not downstream AND that e2e tests would not catch a potential issue.

I think disabling the unit test makes sense here since we will eventually go with 1.20

**Comment by jhrozek** [comment]
PR to temporarily disable unit tests: https://github.com/openshift/release/pull/37515
Now I'll try the e2e tests again..

**Comment by jhrozek** [comment]
@xiaojiey OK, I don't think the amount of changes that would affect tests is so big. I think we should just take these into account:
https://github.com/kubernetes-sigs/security-profiles-operator/commit/57de1effc1a707cd3aabffa95cca6f97969a7244 - the spod resource request is now configurable
https://github.com/kubernetes-sigs/security-profiles-operator/commit/0a8c0f31ba8ceeea37feec211ffc6f078ea9c805 - docs for the above

https://github.com/kubernetes-sigs/security-profiles-operator/commit/998096319108ce44914663a2c9076dea9a6cbee2 - EnableMemoryOptimization
https://github.com/kubernetes-sigs/security-profiles-operator/commit/b04acdf1cfe834dfe29036953061a6e1e1d9a970 - docs for the above

https://github.com/kubernetes-sigs/security-profiles-operator/commit/734f066574405e41388d1cab1721d9112b9461b7 - PriorityClassName
https://github.com/kubernetes-sigs/security-profiles-operator/commit/87c607fa951e2f914bc0a9fd75fd51fdba9ab7f0 - docs for the above

https://github.com/kubernetes-sigs/security-profiles-operator/commit/ff004a2dbd7c0828cb3e7311398a5f0436e93218 - allow using other templates than container

**Comment by jhrozek** [comment]
@sheriff-rh Hi, for the upcoming SPO release for 4.13, I think we should take these doc changes into account and change the downstream docs in a similar way. All three are new tunables in the `spod` resource:
 - https://github.com/kubernetes-sigs/security-profiles-operator/commit/0a8c0f31ba8ceeea37feec211ffc6f078ea9c805
 - https://github.com/kubernetes-sigs/security-profiles-operator/commit/b04acdf1cfe834dfe29036953061a6e1e1d9a970
 - https://github.com/kubernetes-sigs/security-profiles-operator/commit/87c607fa951e2f914bc0a9fd75fd51fdba9ab7f0

Let me know if I should file a card or an issue..

**Comment by jhrozek** [comment]
the cluster didn't install again :-(
/test e2e-operator
/test e2e-flaky

**Comment by jhrozek** [comment]
This is quite ridiculous. Last try before I bring the tests up on forum-testplatform.

/test e2e-operator
/test e2e-flaky

**Comment by jhrozek** [comment]
/test e2e-operator
let's see if everything works better today..

**Comment by jhrozek** [comment]
Flaky tests are known to fail sometimes, let me re-run this..
/test e2e-flaky

**Comment by xiaojiey** [comment]
Verified with payload 4.12.0-0.nightly-2023-03-23-025416 due to the installation bug on Rhel9.
Generally it is good. 
Expect the commit https://github.com/kubernetes-sigs/security-profiles-operator/commit/998096319108ce44914663a2c9076dea9a6cbee2 not verified.
There is minor issue for the message in the event when a non-exists priorityclass applied. The message doesn't helpful at all(seen from the end)
```
###################################Customise the spo daemon resource requirements
$ oc patch spod spod --type merge -p '{"spec":{"daemonResourceRequirements": {"requests": {"memory": "256Mi", "cpu": "250m"}, "limits": {"memory": "512Mi", "cpu": "500m"}}}}'
securityprofilesoperatordaemon.security-profiles-operator.x-k8s.io/spod patched
$ oc get spod/spod -o=jsonpath={.spec.daemonResourceRequirements} | jq -r
{
  "limits": {
    "cpu": "500m",
    "memory": "512Mi"
  },
  "requests": {
    "cpu": "250m",
    "memory": "256Mi"
  }
}
$ oc get pod -l  name=spod -o=jsonpath={.items[*].spec.containers[*].resources} | jq -r
{
  "limits": {
    "cpu": "500m",
    "memory": "512Mi"
  },
  "requests": {
    "cpu": "250m",
    "memory": "256Mi"
  }
}
{
  "limits": {
    "ephemeral-storage": "400Mi",
    "memory": "1Gi"
  },
  "requests": {
    "cpu": "100m",
    "ephemeral-storage": "200Mi",
    "memory": "512Mi"
  }
}
{
  "limits": {
    "ephemeral-storage": "20Mi",
    "memory": "128Mi"
  },
  "requests": {
    "cpu": "50m",
    "ephemeral-storage": "10Mi",
    "memory": "32Mi"
  }
}
{
  "limits": {
    "cpu": "500m",
    "memory": "512Mi"
  },
  "requests": {
    "cpu": "250m",
    "memory": "256Mi"
  }
}
{
  "limits": {
    "ephemeral-storage": "400Mi",
    "memory": "1Gi"
  },
  "requests": {
    "cpu": "100m",
    "ephemeral-storage": "200Mi",
    "memory": "512Mi"
  }
}
{
  "limits": {
    "ephemeral-storage": "20Mi",
    "memory": "128Mi"
  },
  "requests": {
    "cpu": "50m",
    "ephemeral-storage": "10Mi",
    "memory": "32Mi"
  }
}
{
  "limits": {
    "cpu": "500m",
    "memory": "512Mi"
  },
  "requests": {
    "cpu": "250m",
    "memory": "256Mi"
  }
}
{
  "limits": {
    "ephemeral-storage": "400Mi",
    "memory": "1Gi"
  },
  "requests": {
    "cpu": "100m",
    "ephemeral-storage": "200Mi",
    "memory": "512Mi"
  }
}
{
  "limits": {
    "ephemeral-storage": "20Mi",
    "memory": "128Mi"
  },
  "requests": {
    "cpu": "50m",
    "ephemeral-storage": "10Mi",
    "memory": "32Mi"
  }
}
{
  "limits": {
    "cpu": "500m",
    "memory": "512Mi"
  },
  "requests": {
    "cpu": "250m",
    "memory": "256Mi"
  }
}
{
  "limits": {
    "ephemeral-storage": "400Mi",
    "memory": "1Gi"
  },
  "requests": {
    "cpu": "100m",
    "ephemeral-storage": "200Mi",
    "memory": "512Mi"
  }
}
{
  "limits": {
    "ephemeral-storage": "20Mi",
    "memory": "128Mi"
  },
  "requests": {
    "cpu": "50m",
    "ephemeral-storage": "10Mi",
    "memory": "32Mi"
  }
}
{
  "limits": {
    "cpu": "500m",
    "memory": "512Mi"
  },
  "requests": {
    "cpu": "250m",
    "memory": "256Mi"
  }
}
{
  "limits": {
    "ephemeral-storage": "400Mi",
    "memory": "1Gi"
  },
  "requests": {
    "cpu": "100m",
    "ephemeral-storage": "200Mi",
    "memory": "512Mi"
  }
}
{
  "limits": {
    "ephemeral-storage": "20Mi",
    "memory": "128Mi"
  },
  "requests": {
    "cpu": "50m",
    "ephemeral-storage": "10Mi",
    "memory": "32Mi"
  }
}
{
  "limits": {
    "cpu": "500m",
    "memory": "512Mi"
  },
  "requests": {
    "cpu": "250m",
    "memory": "256Mi"
  }
}
{
  "limits": {
    "ephemeral-storage": "400Mi",
    "memory": "1Gi"
  },
  "requests": {
    "cpu": "100m",
    "ephemeral-storage": "200Mi",
    "memory": "512Mi"
  }
}
{
  "limits": {
    "ephemeral-storage": "20Mi",
    "memory": "128Mi"
  },
  "requests": {
    "cpu": "50m",
    "ephemeral-storage": "10Mi",
    "memory": "32Mi"
  }
##############create a selinux tempalte other than container
1. create with spod patch
$ oc apply -f -<<EOF
apiVersion: security-profiles-operator.x-k8s.io/v1alpha2
kind: SelinuxProfile
metadata:
  name: net-container-policy
spec:
  inherit:
    - name: net_container
  allow:
    var_run_t:
      sock_file:
        - write
EOF
$ oc get selinuxprofiles.security-profiles-operator.x-k8s.io
NAME                   USAGE                                                     STATE
net-container-policy   net-container-policy_security-profiles-operator.process   Error
$ oc get events --field-selector reason=CannotSaveSelinuxPolicy
LAST SEEN   TYPE      REASON                    OBJECT                                MESSAGE
7s          Warning   CannotSaveSelinuxPolicy   selinuxprofile/net-container-policy   Profile failed validation on ip-10-0-214-136.us-east-2.compute.internal: system profile net_container not in SecurityProfilesOperatorDaemon's allow list: system profile not allowed
2s          Warning   CannotSaveSelinuxPolicy   selinuxprofile/net-container-policy   Profile failed validation on ip-10-0-169-66.us-east-2.compute.internal: system profile net_container not in SecurityProfilesOperatorDaemon's allow list: system profile not allowed
13s         Warning   CannotSaveSelinuxPolicy   selinuxprofile/net-container-policy   Profile failed validation on ip-10-0-181-79.us-east-2.compute.internal: system profile net_container not in SecurityProfilesOperatorDaemon's allow list: system profile not allowed
11s         Warning   CannotSaveSelinuxPolicy   selinuxprofile/net-container-policy   Profile failed validation on ip-10-0-136-237.us-east-2.compute.internal: system profile net_container not in SecurityProfilesOperatorDaemon's allow list: system profile not allowed
20s         Warning   CannotSaveSelinuxPolicy   selinuxprofile/net-container-policy   Profile failed validation on ip-10-0-148-83.us-east-2.compute.internal: system profile net_container not in SecurityProfilesOperatorDaemon's allow list: system profile not allowed
18s         Warning   CannotSaveSelinuxPolicy   selinuxprofile/net-container-policy   Profile failed validation on ip-10-0-222-0.us-east-2.compute.internal: system profile net_container not in SecurityProfilesOperatorDaemon's allow list: system profile not allowed
2. create selinuxprofile after patch:
$ oc  patch spod spod --type=merge -p '{"spec":{"selinuxOptions":{"allowedSystemProfiles":["container","net_container"]}}}'
securityprofilesoperatordaemon.security-profiles-operator.x-k8s.io/spod patched 
$  oc delete selinuxprofile net-container-policy
selinuxprofile.security-profiles-operator.x-k8s.io "net-container-policy" deleted
]$ oc apply -f -<<EOF                                            
apiVersion: security-profiles-operator.x-k8s.io/v1alpha2
kind: SelinuxProfile
metadata:
  name: net-container-policy
spec:
  inherit:
    - name: net_container
  allow:
    var_run_t:
      sock_file:
        - write
EOF
selinuxprofile.security-profiles-operator.x-k8s.io/net-container-policy created
$ oc get selinuxprofiles.security-profiles-operator.x-k8s.io -w
NAME                   USAGE                                                     STATE
net-container-policy   net-container-policy_security-profiles-operator.process   InProgress
net-container-policy   net-container-policy_security-profiles-operator.process   Installed

##########PriorityClass
1. check default priorityclass name:
$ oc get spod/spod -o=jsonpath={.spec.priorityClassName}
system-node-critical
2. create a custom priorityclass:
$ oc apply -f -<<EOF
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: my-priority-class
value: 99
globalDefault: false
description: "This priority class should be used for XYZ service pods only."
EOF
priorityclass.scheduling.k8s.io/my-priority-class created

$ oc get pc my-priority-class
NAME        VALUE   GLOBAL-DEFAULT   AGE
my-priority-class   99      false            17s
3. patch it:
$ oc  patch spod spod --type=merge -p '{"spec":{"priorityClassName":"my-priority-class"}}'
securityprofilesoperatordaemon.security-profiles-operator.x-k8s.io/spod patched
$ oc get pod -l name=spod
NAME         READY   STATUS    RESTARTS   AGE
spod-8cxwb   3/3     Running   0          88s
spod-9kflk   3/3     Running   0          88s
spod-l46z5   3/3     Running   0          88s
spod-rzpn4   3/3     Running   0          88s
spod-slr5s   3/3     Running   0          88s
spod-z8g5c   3/3     Running   0          88s
4. check spod pods
$ oc get pod -l  name=spod -o=jsonpath={.items[*].spec.priorityClassName}
my-priority-class my-priority-class my-priority-class my-priority-class my-priority-class my-priority-class
###################################Deploy a non-exist priorityclass name
$ oc -n openshift-security-profiles patch spod spod --type=merge -p '{"spec":{"priorityClassName":"priority-class-not-exist "}}'
$ oc get events --field-selector reason=CannotUpdateSPOD
LAST SEEN   TYPE      REASON             OBJECT                                MESSAGE
4m49s       Warning   CannotUpdateSPOD   securityprofilesoperatordaemon/spod   updating operator DaemonSet: DaemonSet.apps "spod" is invalid: spec.template.spec.priorityClassName: Invalid value: "priority-class-not-exist ": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

```

**Comment by jhrozek** [comment]
> There is minor issue for the message in the event when a non-exists priorityclass applied. The message doesn't helpful at all(seen from the end)

I don't think this is something that SPO can fix, this comes from kube..

**Comment by jhrozek** [comment]
docs agreed on slack
QE testing here in this PR in an earlier comment

**Comment by xiaojiey** [comment]
Verification pass for  the commit https://github.com/kubernetes-sigs/security-profiles-operator/commit/998096319108ce44914663a2c9076dea9a6cbee2.
Test steps seen from below:
```
1. install SPO
2.  $ oc -n openshift-security-profiles patch spod spod --type=merge -p '{"spec":{"enableLogEnricher":true,"enableMemoryOptimization":true}}'
3. Create a ns mytest1, add label for ns mytest1, create profilebinding, create a pod without label spo.x-k8s.io/enable-recording=true, and delete pod;
4. Create another ns mytest2,add label for ns mytest1, create profilebinding, create a pod with label spo.x-k8s.io/enable-recording=true, and delete pod;
5. Check the selinuxprofiles will be not be created in ns mytest1, but will be created in ns mytest2
Details could be seen from ploarion test case OCP-61599
```

**Pull request merged**
