### PR TITLE
CMP-1679: selinux: Add a permissive boolean

### PR DESCRIPTION
**Pull request by jhrozek**
Similarly to how seccomp profiles allow setting the default action to LOG, let's allow the selinux profiles to be set to permissive mode. This way, all calls would have still be allowed, but would appear in audit.log.

This is useful in case the user is just iterating on a policy and wants to deploy a first version of the policy in the wild without causing AVC denials.

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by jhrozek** [comment]
QE: Please see the upstream test for instructions, but tl;dr is to create a SELinux policy, remove some actions that are needed for the policy, set permissive: true and make sure the workload still works fine. Bonus points if we can ensure that the removed action gets caught in audit.log (but that would probably require scheduling the workload on one node only..or a DS..)

**Comment by jhrozek** [comment]
@sheriff-rh this is one of the few patches that might have an effect on docs. There is a blob in this PR that changes installation-usage.md, is that good enough for downstream docs?

**Comment by jhrozek** [comment]
@mkumku PTAL for px-approved

**Comment by sheriff-rh** [comment]
Hey @jhrozek, I can add that to the docs. Would an example look like this, and is `true` all lowercase?
```apiVersion: security-profiles-operator.x-k8s.io/v1alpha2
kind: SelinuxProfile
metadata:
  name: nginx-secure
  namespace: nginx-deploy
spec:
  permissive: true```

**Comment by jhrozek** [comment]
> Hey @jhrozek, I can add that to the docs. Would an example look like this, and is `true` all lowercase?
> 
> ```
> kind: SelinuxProfile
> metadata:
>   name: nginx-secure
>   namespace: nginx-deploy
> spec:
>   permissive: true
> ```

thank you!

Yes, permissive is right under .spec and lowecase true is the most common form of expressing boolean

**Comment by jhrozek** [comment]
@Vincent056 can you lgtm?

**Comment by xiaojiey** [comment]
Pre-merge test pass with 4.13.0-0.nightly-2022-11-17-094851 + code in the PR:
There is no new test cases in the test. The same with test case in the PR.
1. Deploy SPO
2. Create a new namespace mytest
3. In namespace mytest, verifiy a pod with a incomplete selinuxprofile with permissive boolean setting to false/true. When it is setting to false, it is enforcing mode;  thus the pod will in error status as permission denied. While it is setting to true, it is permissive mode; thus pod will be running. 
```
$ oc apply -f -<<EOF
apiVersion: security-profiles-operator.x-k8s.io/v1alpha2
kind: SelinuxProfile
metadata:
  name: errorlogger-incomplete-enforcing
spec:
  permissive: false
  allow:
    var_log_t:
      dir:
        - getattr
        - lock
        - search
        - ioctl
        - add_name
        - remove_name
        - write
      file:
        - getattr
        - read
        - ioctl
        - lock
        - map
        - open
        - create
      sock_file:
        - getattr
        - read
        - write
        - append
        - open
 EOF
 selinuxprofile.security-profiles-operator.x-k8s.io/errorlogger-incomplete-enforcing created
$ oc get selinuxprofiles errorlogger-incomplete-enforcing -w
NAME                               USAGE                                             STATE
errorlogger-incomplete-enforcing   errorlogger-incomplete-enforcing_mytest.process   InProgress
errorlogger-incomplete-enforcing   errorlogger-incomplete-enforcing_mytest.process   Installed
$ oc apply -f -<<EOF
apiVersion: v1
kind: Pod
metadata:
  name: errorlogger
spec:
  containers:
  - name: errorlogger
    image: "registry.access.redhat.com/ubi8/ubi-minimal:latest"
    command: ["/bin/bash"]
    args: ["-c", "set -eux; while true; do echo \"Time: $(date). Some error info.\" >> /var/log/test.log; sleep 2; done"]
    securityContext:
      seLinuxOptions:
        type: errorlogger-incomplete-enforcing_mytest.process
    volumeMounts:
    - name: varlog
      mountPath: /var/log
  restartPolicy: Never
  volumes:
  - name: varlog
    hostPath:
      path: /var/log
      type: Directory
EOF
pod/errorlogger created
$ oc get pod -w
NAME          READY   STATUS   RESTARTS   AGE
errorlogger   0/1     Error    0          4s
errorlogger   0/1     Error    0          5s
$ oc logs pod/errorlogger
+ true
++ date
+ echo 'Time: Fri Nov 18 14:36:26 UTC 2022. Some error info.'
/bin/bash: /var/log/test.log: Permission denied
$ oc delete pod errorlogger 
pod "errorlogger" deleted
-------------------------------------------------------------------------------------------------------

$ oc apply -f -<<EOF
> apiVersion: security-profiles-operator.x-k8s.io/v1alpha2
kind: SelinuxProfile
metadata:
  name: errorlogger-incomplete-permissvie
spec:
  permissive: true
  allow:
    var_log_t:
      dir:
        - getattr
        - lock
        - search
        - ioctl
        - add_name
        - remove_name
        - write
      file:
        - getattr
        - read
        - ioctl
        - lock
        - map
        - open
        - create
      sock_file:
        - getattr
        - read
        - write
        - append
        - open
EOF
selinuxprofile.security-profiles-operator.x-k8s.io/errorlogger-incomplete-permissvie created
$ oc get selinuxprofiles.security-profiles-operator.x-k8s.io -w
NAME                                USAGE                                              STATE
errorlogger-incomplete-enforcing    errorlogger-incomplete-enforcing_mytest.process    Installed
errorlogger-incomplete-permissvie   errorlogger-incomplete-permissvie_mytest.process   InProgress
errorlogger-incomplete-permissvie   errorlogger-incomplete-permissvie_mytest.process   Installed
^C
$ oc apply -f -<<EOF
apiVersion: v1
kind: Pod
metadata:
  name: errorlogger
spec:
  containers:
  - name: errorlogger
    image: "registry.access.redhat.com/ubi8/ubi-minimal:latest"
    command: ["/bin/bash"]
    args: ["-c", "set -eux; while true; do echo \"Time: $(date). Some error info.\" >> /var/log/test.log; sleep 2; done"]
    securityContext:
      seLinuxOptions:
        type: errorlogger-incomplete-permissvie_mytest.process
    volumeMounts:
    - name: varlog
      mountPath: /var/log
  restartPolicy: Never
  volumes:
  - name: varlog
    hostPath:
      path: /var/log
      type: Directory
EOF
pod/errorlogger created
$ $ oc get pod -w
NAME          READY   STATUS    RESTARTS   AGE
errorlogger   1/1     Running   0          8s
^C$ oc logs pod/errorlogger
+ true
++ date
+ echo 'Time: Fri Nov 18 14:43:23 UTC 2022. Some error info.'
+ sleep 2
+ true
++ date
+ echo 'Time: Fri Nov 18 14:43:25 UTC 2022. Some error info.'
+ sleep 2
+ true
++ date

```

**Comment by jhrozek** [comment]
doc-approved because this is already in the docs
qe-approved per Xiaojie's comment
px-approved per Marina's reply on Slack

**Pull request merged**
