### PR TITLE
Isolate OpenShift maintainer commits from main branch

### PR DESCRIPTION
**Pull request by rhmdnd**
Include OpenShift maintainer commits in their own OCP branch.

Ideally, this will be rebased on top of the main branch periodically when we do releases.

### CODE REVIEW

**Review by Vincent056 — APPROVED** [review]
/lgtm

**Comment by xiaojiey** [comment]
@rhmdnd Could you also add @BhargaviGudi into the approvers list? Thanks.

**Review by saschagrunert — APPROVED** [review]

**Comment by rhmdnd** [comment]
> @rhmdnd Could you also add @BhargaviGudi into the approvers list? Thanks.

Done - thanks!

**Pull request merged**
