### PR TITLE
Sync 0.7.1 for OCP 4.13 release

### PR DESCRIPTION
**Pull request by jhrozek**
There's really nothing to test or document here, the main reason is to bring the 0.7.1 tag to OCP.

### CODE REVIEW

**Comment by jhrozek** [comment]
registries appear to be down..

**Comment by jhrozek** [comment]
/retest
the outage should be resolved

**Comment by jhrozek** [comment]
umm this time the build failed but I don't see why. And the images job has succeeded..

**Comment by jhrozek** [comment]
the registries are down again probably:
```
 [1/2] STEP 1/11: FROM registry.access.redhat.com/ubi8/go-toolset@sha256:160ff3bc88c4921f7b602f56b6115fe8bc99212f81f1d5acf5c259210d0261f3 AS build
Trying to pull registry.access.redhat.com/ubi8/go-toolset@sha256:160ff3bc88c4921f7b602f56b6115fe8bc99212f81f1d5acf5c259210d0261f3...
error: build error: error creating build container: initializing source docker://registry.access.redhat.com/ubi8/go-toolset@sha256:160ff3bc88c4921f7b602f56b6115fe8bc99212f81f1d5acf5c259210d0261f3: can't talk to a V1 container registry 
```

**Comment by jhrozek** [comment]
This time it looks like the regular e2e succeeded, but the gather step failed and the flaky test failed in one of the tests.
/retest

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
