### PR TITLE
Auto-select selinuxd image based on nodeInfo.OSImage

### PR DESCRIPTION
**Pull request by jhrozek**
Cluster nodes might be upgraded between major OS releases where the libselinux major version is incompatible. This means that the selinuxd image must be based on images matching the OS release and the libselinux major version.

But SPO must also be able to select the images based on what OS are the cluster nodes running.

To implement that, this patch adds a new key to the security-profiles-operator-profile configmap that maps regexes matching nodeInfo.OSImage to selinuxd images. The operator then selects the right selinuxd image, falling back to using the RELATED_IMAGE environment variable.

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by jhrozek** [comment]
@xiaojiey not sure if you want to test this PR now or later in downstream. But the way to test this now would be to:

-  deploy SPO with make deploy-opeshift-dev
- on RHEL-8 inspect that the selinuxd image was autoselected to quay.io/security-profiles-operator/selinuxd-el8:latest
- on RHEL-9 inspect that the  selinuxd image was autoselected to quay.io/security-profiles-operator/selinuxd-el9:latest

**Comment by xiaojiey** [comment]
Verified with both 4.13 and 4.12 clusters, the  seliuxd image auto-selection works as expected. 
==========verified with a 4.13 cluster
$ make deploy-openshift-dev
podman build -f Dockerfile.ubi --build-arg version=0.7.1 -t security-profiles-operator:latest .
[1/2] STEP 1/10: FROM registry.access.redhat.com/ubi8/go-toolset@sha256:160ff3bc88c4921f7b602f56b6115fe8bc99212f81f1d5acf5c259210d0261f3 AS build
...
configmap/security-profiles-operator-profile created
secret/metrics-token created
deployment.apps/security-profiles-operator created
mutatingwebhookconfiguration.admissionregistration.k8s.io/spo-mutating-webhook-configuration created
Setting triggers to track image
oc set triggers -n security-profiles-operator deployment/security-profiles-operator --from-image openshift/security-profiles-operator:latest -c security-profiles-operator
deployment.apps/security-profiles-operator triggers updated
$ oc get pod
NAME                                                 READY   STATUS    RESTARTS   AGE
security-profiles-operator-5f4d6cd95-9h2vw           1/1     Running   0          70s
security-profiles-operator-5f4d6cd95-jxpnh           1/1     Running   0          60s
security-profiles-operator-5f4d6cd95-sw4j2           1/1     Running   0          65s
security-profiles-operator-webhook-b58c66f48-2rnlb   1/1     Running   0          66s
security-profiles-operator-webhook-b58c66f48-cn88b   1/1     Running   0          66s
security-profiles-operator-webhook-b58c66f48-g7h5j   1/1     Running   0          66s
spod-fd86h                                           3/3     Running   0          44s
spod-hhk65                                           3/3     Running   0          44s
spod-ksgrh                                           3/3     Running   0          44s
spod-pgrfm                                           3/3     Running   0          44s
spod-qq5c8                                           3/3     Running   0          44s
spod-svgbt                                           3/3     Running   0          44s
$ oc get spod
NAME   STATE
spod   RUNNING
$ oc get  pod/spod-fd86h -o yaml | grep image:
    image: image-registry.openshift-image-registry.svc:5000/openshift/security-profiles-operator@sha256:d374d8dee1a76a5204265c9065ee5b1cb545a10879e147a8bacdb1e970896425
    image: quay.io/security-profiles-operator/selinuxd-el9:latest
    image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
    image: image-registry.openshift-image-registry.svc:5000/openshift/security-profiles-operator@sha256:d374d8dee1a76a5204265c9065ee5b1cb545a10879e147a8bacdb1e970896425
    image: quay.io/security-profiles-operator/selinuxd-el9:latest
    image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
    image: image-registry.openshift-image-registry.svc:5000/openshift/security-profiles-operator@sha256:d374d8dee1a76a5204265c9065ee5b1cb545a10879e147a8bacdb1e970896425
    image: quay.io/security-profiles-operator/selinuxd-el9:latest
    image: image-registry.openshift-image-registry.svc:5000/openshift/security-profiles-operator@sha256:d374d8dee1a76a5204265c9065ee5b1cb545a10879e147a8bacdb1e970896425
    image: quay.io/security-profiles-operator/selinuxd-el9:latest

==========verified with a 4.12 cluster
$ oc get clusterversion
NAME      VERSION                              AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.12.0-0.nightly-2023-04-07-211226   True        False         87m     Cluster version is 4.12.0-0.nightly-2023-04-07-211226
$ oc project security-profiles-operator 
Now using project "security-profiles-operator" on server "https://api.jiasun-0410a.qe.devcluster.openshift.com:6443".
$ oc get pod
NAME                                                  READY   STATUS            RESTARTS   AGE
security-profiles-operator-666d8d9bc9-krg75           1/1     Running           0          2m6s
security-profiles-operator-666d8d9bc9-ndzk7           1/1     Running           0          2m18s
security-profiles-operator-666d8d9bc9-p9mk4           1/1     Running           0          2m12s
security-profiles-operator-webhook-6c4778bc58-dq2vt   1/1     Running           0          2m13s
security-profiles-operator-webhook-6c4778bc58-fw2wz   1/1     Running           0          2m13s
security-profiles-operator-webhook-6c4778bc58-n2k6w   1/1     Running           0          2m13s
spod-5ndpj                                            3/3     Running           0          76s
spod-p7nwq                                            3/3     Running           0          75s
spod-pjg2t                                            0/3     PodInitializing   0          75s
spod-q6m7l                                            0/3     Init:1/2          0          76s
spod-slljh                                            3/3     Running           0          75s
spod-tprvv                                            3/3     Running           0          75s
$ oc get pod/spod-5ndpj
NAME         READY   STATUS    RESTARTS   AGE
spod-5ndpj   3/3     Running   0          108s
$ oc get pod/spod-5ndpj -o yaml | grep image:
    image: image-registry.openshift-image-registry.svc:5000/openshift/security-profiles-operator@sha256:538b6ae374200ab907daf59bc69ed77e170525cbc39b19313d07d73314964d61
    image: quay.io/security-profiles-operator/selinuxd-el8:latest
    image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
    image: image-registry.openshift-image-registry.svc:5000/openshift/security-profiles-operator@sha256:538b6ae374200ab907daf59bc69ed77e170525cbc39b19313d07d73314964d61
    image: quay.io/security-profiles-operator/selinuxd-el8:latest
    image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
    image: image-registry.openshift-image-registry.svc:5000/openshift/security-profiles-operator@sha256:538b6ae374200ab907daf59bc69ed77e170525cbc39b19313d07d73314964d61
    image: quay.io/security-profiles-operator/selinuxd-el8:latest
    image: image-registry.openshift-image-registry.svc:5000/openshift/security-profiles-operator@sha256:538b6ae374200ab907daf59bc69ed77e170525cbc39b19313d07d73314964d61
    image: quay.io/security-profiles-operator/selinuxd-el8:latest

**Pull request merged**
