### PR TITLE
Sync https://issues.redhat.com/browse/CMP-1586 to OCP

### PR DESCRIPTION
**Pull request by jhrozek**
This pr fix seccompprofiles deletion when a node is removed, we added a check to see if node finalizer is a deleted node, if so, we remove such finalizer so the seccompprofile can be deleted without any issues.

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Synces fix for https://issues.redhat.com/browse/CMP-1586 downstream 

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by jhrozek** [comment]
@Vincent056 PTAL

**Comment by jhrozek** [comment]
@sheriff-rh PTAL for doc-approved. Since this is a new version and the bug couldn't have hit any existing customers, I don't think we need to document it. I'm mostly switching SPO to the no-FF process so that we take a look at every patch from now on before the release

**Comment by jhrozek** [comment]
@xiaojiey PTAL for qe-approved. I used https://docs.openshift.com/container-platform/4.8/machine_management/applying-autoscaling.html#cluster-autoscaler-about_applying-autoscaling for my testing. I scaled up a machine set by one machine, installed a policy, scaled it down again and made sure that the policy can be deleted.

**Review by Vincent056 — APPROVED** [review]
/lgtm

**Comment by sheriff-rh** [comment]
Agreed with no doc impact. Setting doc-approved.

**Review by saschagrunert — APPROVED** [review]

**Comment by xiaojiey** [comment]
Pre-merge verification pass.
1. install SPO from source code with this PR
2. create a new namespace called test and create a seccompprofile in test 
3. Scaledown replicas in one machineset from 1 to 0:
$  oc scale --replicas=0 machineset xiyuan04-pr-s84m6-worker-us-east-2a  -n openshift-machine-api
machineset.machine.openshift.io/xiyuan04-pr-s84m6-worker-us-east-2a scaled
$ oc get machineset  -n openshift-machine-api
NAME                                  DESIRED   CURRENT   READY   AVAILABLE   AGE
xiyuan04-pr-s84m6-worker-us-east-2a   0         0                             5h27m
xiyuan04-pr-s84m6-worker-us-east-2b   1         1         1       1           5h27m
xiyuan04-pr-s84m6-worker-us-east-2c   1         1         1       1           5h27m
4. check the finalizers was removed for the seccompprofile
5. Tried to delete seccompprofile
6. Also tried scenario: create seccompprofile, then scaleup  replicas in one machineset from 0 to 2: the finalizers will be added for the seccompprofile; then  scaleup  replicas in one machineset from 2 to 1, the finalizers for the node was removed for the seccompprofile, the seccompprofile could be deleted successfully.

**Comment by xiaojiey** [comment]
Pre-merge verification pass.
1. install SPO from source code with this PR
2. create a new namespace called test and create a seccompprofile in test 
3. Scaledown replicas in one machineset from 1 to 0:
$  oc scale --replicas=0 machineset xiyuan04-pr-s84m6-worker-us-east-2a  -n openshift-machine-api
machineset.machine.openshift.io/xiyuan04-pr-s84m6-worker-us-east-2a scaled
$ oc get machineset  -n openshift-machine-api
NAME                                  DESIRED   CURRENT   READY   AVAILABLE   AGE
xiyuan04-pr-s84m6-worker-us-east-2a   0         0                             5h27m
xiyuan04-pr-s84m6-worker-us-east-2b   1         1         1       1           5h27m
xiyuan04-pr-s84m6-worker-us-east-2c   1         1         1       1           5h27m
4. check the finalizers was removed for the seccompprofile
5. Tried to delete seccompprofile
6. Also tried scenario: create seccompprofile, then scaleup  replicas in one machineset from 0 to 2: the finalizers will be added for the seccompprofile; then  scaleup  replicas in one machineset from 2 to 1, the finalizers for the node was removed for the seccompprofile, the seccompprofile could be deleted successfully.

**Comment by jhrozek** [comment]
No no-FF acks were provided verbally because the repo access was misconfigured, so I added them myself (this should be fixed now that PR #11 is merged)

**Pull request merged**
