### PR TITLE
recordingmerger: Fix producing union of SELinux permissions

### PR DESCRIPTION
**Pull request by jhrozek**
We were naively appending all permissions from the SELinux profile about to be merged, this was causing potential duplicates. Let's check if the permission is already present before merging it.

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Syncs a bugfix for https://issues.redhat.com/browse/CMP-1673 to downstream

#### Which issue(s) this PR fixes:
[CMP-1673](https://issues.redhat.com/browse/CMP-1673)

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by jhrozek** [comment]
@Vincent056 PTAL

**Comment by jhrozek** [comment]
@xiaojiey PTAL for QE ack. In general the issue happens when two policies record the same AVCs, then the merged policy will contain duplicates. I /think/ that trying to record e.g. the same nginx behaviour twice (so, run a deploy whilte recording it, delete the pods, keep recording also the new ones, then delete the recording) would have triggered the bug. But I'm not sure we need to spend too much time on a test case, there are unit tests upstream (see the patch)

**Comment by jhrozek** [comment]
@sheriff-rh PTAL for doc-approved. Since this is a new version and the bug couldn't have hit any existing customers, I don't think we need to document it. I'm mostly switching SPO to the no-FF process so that we take a look at every patch from now on before the release

**Comment by sheriff-rh** [comment]
Agreed with no impact to docs. Doc-approved.

(I do not have access to set labels in this repo).

**Review by saschagrunert — APPROVED** [review]

**Comment by jhrozek** [comment]
Marina provided the px-approved on Slack while the permissions on the repo are being fixed (PR #11)

**Comment by xiaojiey** [comment]
Pre-merge verification pass with 4.13.0-0.nightly-2022-11-17-094851 + latest code
$ git log | head
commit 3bbab1a419ca5cf708c1a6ba3f9fc134bd29ab6d
Author: Jakub Hrozek <jhrozek@redhat.com>
Date:   Mon Oct 24 10:50:06 2022 +0200

    recordingmerger: Fix producing union of SELinux permissions
    
    We were naively appending all permissions from the SELinux profile about
    to be merged, this was causing potential duplicates. Let's check if the
    permission is already present before merging it.
```
1. deploy cluster 
$ make deploy-openshift-dev
podman build -f Dockerfile.ubi --build-arg version=0.5.0 -t security-profiles-operator:latest .
[1/2] STEP 1/9: FROM registry.fedoraproject.org/fedora-minimal@sha256:b676cdd0fdefe33124325082d070c39558f1966a63dfd1193681a7900707d332 AS build
[1/2] STEP 2/9: USER root
--> Using cache 8e46d87ebcfae07930ba68c15e56df67d28992ab793651893b6f635e1c4496bd
--> 8e46d87ebcf
[1/2] STEP 3/9: WORKDIR /work
--> Using cache 50df47ee377e0decd4f8745e49142341461cb473948a4196e61dec01350b40da
...
2. Patch cluster to enable log enricher:
$  oc patch spod spod --type=merge -p '{"spec":{"enableLogEnricher":true}}' -n security-profiles-operator
securityprofilesoperatordaemon.security-profiles-operator.x-k8s.io/spod patched
3. Create a namespace, label it:
$ oc new-project mytest
$ oc label ns mytest spo.x-k8s.io/enable-recording="true" 
namespace/mytest labeled
$ oc apply -f -<<EOF
apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: ProfileRecording
metadata:
  name: spo-recording
spec:
  kind: SelinuxProfile
  recorder: logs
  podSelector:
    matchLabels:
       name: hello-daemonset
EOF

profilerecording.security-profiles-operator.x-k8s.io/spo-recording created
$ oc create -f -<<EOF
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: spo-record-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: spo-record
  namespace: mytest
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - privileged
  verbs:
  - use
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spo-record
  namespace: mytest
subjects:
- kind: ServiceAccount
  name: spo-record-sa
roleRef:
  kind: Role
  name: spo-record
  apiGroup: rbac.authorization.k8s.io
EOF
serviceaccount/spo-record-sa created
role.rbac.authorization.k8s.io/spo-record created
rolebinding.rbac.authorization.k8s.io/spo-record created
$ oc label ns mytest security.openshift.io/scc.podSecurityLabelSync=false pod-security.kubernetes.io/enforce=privileged --overwrite=trueue
namespace/mytest labeled
$ oc apply -f -<<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-openshift
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-openshift
  template:
    metadata:
      labels:
        app: hello-openshift
    spec:
      serviceAccountName: spo-record-sa
      initContainers:
      - name: wait
        image: quay.io/openshifttest/centos:centos7
        command: ["/bin/sh", "-c", "env"]
      containers:
      - name: hello-openshift
        image: quay.io/openshifttest/hello-openshift:multiarch
        ports:
        - containerPort: 80
      - name: hello-openshift2
        image: quay.io/openshifttest/hello-openshift:multiarch-fedora
        ports:
        - containerPort: 81
EOF
deployment.apps/hello-openshift created
$ oc delete deployment  hello-openshift
deployment.apps "hello-openshift" deleted
[xiyuan@MiWiFi-RA69-srv security-profiles-operator (pr-9)]$ oc get selinuxprofiles.security-profiles-operator.x-k8s.io 
NAME                                    USAGE                                                  STATE
test-recording-hello-openshift-mgc87    test-recording-hello-openshift-mgc87_mytest.process    Partial
test-recording-hello-openshift-rv7kz    test-recording-hello-openshift-rv7kz_mytest.process    Partial
test-recording-hello-openshift-v48pd    test-recording-hello-openshift-v48pd_mytest.process    Partial
test-recording-hello-openshift2-mgc87   test-recording-hello-openshift2-mgc87_mytest.process   Partial
test-recording-hello-openshift2-rv7kz   test-recording-hello-openshift2-rv7kz_mytest.process   Partial
test-recording-hello-openshift2-v48pd   test-recording-hello-openshift2-v48pd_mytest.process   Partial
$ oc create -f -<<EOF
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: hello-openshift
  name: hello
  namespace: mytest
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-openshift
    spec:
      containers:
      - name: redis
        image: quay.io/security-profiles-operator/redis:6.2.1
      restartPolicy: Never
      serviceAccount: spo-record-sa
      serviceAccountName: spo-record-sa
      terminationGracePeriodSeconds: 30
EOF
job.batch/hello created
$ oc get pod -w
NAME          READY   STATUS              RESTARTS   AGE
hello-4dlgr   0/1     ContainerCreating   0          4s
hello-4dlgr   1/1     Running             0          7s
$ oc delete job hello
job.batch "hello" deleted
$ oc get selinuxprofiles.security-profiles-operator.x-k8s.io  -w
NAME                                    USAGE                                                  STATE
test-recording-hello-openshift-mgc87    test-recording-hello-openshift-mgc87_mytest.process    Partial
test-recording-hello-openshift-rv7kz    test-recording-hello-openshift-rv7kz_mytest.process    Partial
test-recording-hello-openshift-v48pd    test-recording-hello-openshift-v48pd_mytest.process    Partial
test-recording-hello-openshift2-mgc87   test-recording-hello-openshift2-mgc87_mytest.process   Partial
test-recording-hello-openshift2-rv7kz   test-recording-hello-openshift2-rv7kz_mytest.process   Partial
test-recording-hello-openshift2-v48pd   test-recording-hello-openshift2-v48pd_mytest.process   Partial
test-recording-redis-4dlgr                                                                     
test-recording-redis-4dlgr                                                                     
test-recording-redis-4dlgr                                                                     
test-recording-redis-4dlgr              test-recording-redis-4dlgr_mytest.process              Partial

$  oc get selinuxprofiles test-recording-hello-openshift2 -o=jsonpath={.spec} | jq -r
{
  "allow": {
    "@self": {
      "tcp_socket": [
        "listen"
      ]
    },
    "http_cache_port_t": {
      "tcp_socket": [
        "name_bind"
      ]
    },
    "node_t": {
      "tcp_socket": [
        "node_bind"
      ]
    },
    "redis_port_t": {
      "tcp_socket": [
        "name_bind"
      ]
    },
    "transproxy_port_t": {
      "tcp_socket": [
        "name_bind"
      ]
    },
    "unreserved_port_t": {
      "tcp_socket": [
        "name_bind"
      ]
    }
  },
  "inherit": [
    {
      "kind": "System",
      "name": "container"
    }
  ]
}


Additional info: before the PR, the result looks like below:
$ oc get selinuxprofiles test-recording-hello-openshift2 -o=jsonpath={.spec} | jq -r
{
  "allow": {
    "@self": {
      "tcp_socket": [
        "listen"
      ]
    },
    "http_cache_port_t": {
      "tcp_socket": [
        "name_bind"
      ]
    },
    "node_t": {
      "tcp_socket": [
        "node_bind"
      ]
    },
    "redis_port_t": {
      "tcp_socket": [
        "name_bind"
      ]
    },
    "transproxy_port_t": {
      "tcp_socket": [
        "name_bind",
        "name_bind",
        "name_bind"
      ]
    },
    "unreserved_port_t": {
      "tcp_socket": [
        "name_bind"
      ]
    }
  },
  "inherit": [
    {
      "kind": "System",
      "name": "container"
    }
```

**Pull request merged**
