### PR TITLE
synchronize with upstream

### PR DESCRIPTION
**Pull request by jhrozek**
#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by jhrozek** [comment]
Hmm:
```
         --- FAIL: TestSuite/TestSecurityProfilesOperator/cluster-wide:_Seccomp:_make_sure_statuses_for_profiles_with_long_names_can_be_listed (37.82s) 
```
this is the second time the test failed in OCP despite being fixed lately in upstream.

I'm going to add some debugging patch to the PR and in the meantime hold it. In the debug logs I do see that all six nodes were represented in the nodeStatus. Weird.

@saschagrunert thanks for the review, but please don't waste your time until I fix the tests, there might be some test patches just to see what's going on.

/hold

**Comment by jhrozek** [comment]
> @jhrozek: all tests **passed!**
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openshift&repo=security-profiles-operator&pr=3). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:jhrozek).

Woo!

Going to submit that patch upstream.

**Comment by jhrozek** [comment]
/hold cancel
@saschagrunert lgtm please :-)

**Review by saschagrunert — APPROVED** [review]
Awesome work!
/lgtm

**Pull request merged**
