### PR TITLE
Update v0.8.2

### PR DESCRIPTION
**Pull request by rhmdnd**

### CODE REVIEW

**Comment by BhargaviGudi** [comment]
Verification passed with 4.15.0-0.nightly-2024-01-15-022811 + security-profile-operator from PR #46 
Scenario 1: Regression test: **Passed**
Scenario 2: Upgrade SPO from v0.8.0: **Passed**
1. Created index image from the PR #46 bundle image
2. Installed security-profiles-operator.v0.8.0
<pre>$ oc get csv
NAME                                DISPLAY                      VERSION   REPLACES   PHASE
security-profiles-operator.v0.8.0   Security Profiles Operator   0.8.0                Succeeded
$ oc get pods
NAME                                                  READY   STATUS    RESTARTS   AGE
security-profiles-operator-7cdbb94cbf-8r28l           1/1     Running   0          2m25s
security-profiles-operator-7cdbb94cbf-lm9gc           1/1     Running   0          2m25s
security-profiles-operator-7cdbb94cbf-z67px           1/1     Running   0          2m25s
security-profiles-operator-webhook-677887bb5d-4tvjv   1/1     Running   0          2m14s
security-profiles-operator-webhook-677887bb5d-m6w5m   1/1     Running   0          2m14s
security-profiles-operator-webhook-677887bb5d-nhzmp   1/1     Running   0          2m14s
spod-2t6px                                            4/4     Running   0          2m14s
spod-9tzk5                                            4/4     Running   0          2m14s
spod-g74nz                                            4/4     Running   0          2m14s
spod-htltn                                            4/4     Running   0          2m14s
spod-m8tpp                                            4/4     Running   0          2m14s
spod-wnw8v                                            4/4     Running   0          2m14s
$ oc get sub
NAME                             PACKAGE                      SOURCE             CHANNEL
security-profiles-operator-sub   security-profiles-operator   redhat-operators   release-alpha-rhel-8
</pre>
4. Upgraded to security-profiles-operator.v0.8.2 using index image from the PR
<pre>$ oc patch subscriptions security-profiles-operator-sub -n openshift-security-profiles -p '{"spec":{"channel":"stable","source":"qe-app-registry"}}' --type='merge'
subscription.operators.coreos.com/security-profiles-operator-sub patched
$ oc get sub
NAME                             PACKAGE                      SOURCE            CHANNEL
security-profiles-operator-sub   security-profiles-operator   qe-app-registry   stable
$ oc get csv
NAME                                DISPLAY                      VERSION   REPLACES                            PHASE
security-profiles-operator.v0.8.2   Security Profiles Operator   0.8.2     security-profiles-operator.v0.8.0   Succeeded
$ oc get pods
NAME                                                 READY   STATUS    RESTARTS   AGE
security-profiles-operator-f947449bf-7z4rm           1/1     Running   0          9m23s
security-profiles-operator-f947449bf-j82gv           1/1     Running   0          9m28s
security-profiles-operator-f947449bf-pxkzn           1/1     Running   0          9m17s
security-profiles-operator-webhook-7896775d4-4xs8p   1/1     Running   0          8m56s
security-profiles-operator-webhook-7896775d4-654mm   1/1     Running   0          8m50s
security-profiles-operator-webhook-7896775d4-m5svk   1/1     Running   0          8m52s
spod-4xczl                                           4/4     Running   0          8m54s
spod-5zqnj                                           4/4     Running   0          8m54s
spod-knrjc                                           4/4     Running   0          8m54s
spod-lmzk8                                           4/4     Running   0          8m54s
spod-m9qjs                                           4/4     Running   0          8m54s
spod-z5ll7                                           4/4     Running   0          8m54s
</pre>

**Review by BhargaviGudi — APPROVED** [review]

**Review by yuumasato — APPROVED** [review]
/lgtm

**Pull request merged**
